Brand: Nexus
Name: NexusMetaData
Version: 1.0.0
---
Version: 0.14.2
ReleaseDate: 2022-07-14
ReleaseNotes:
- Hot Fix Patch 0.14.2 added 8/10/22.
- Added ability to run Python scripts from Tools tab using Run Script button.
- Added ability to integrate user defined XTool scripts directly into the Explorer GUI. Documentation on how to do this provided.
- Added a LOT more documentation including a Python primer and XLib cookbook.
- Removed Python 3.9.6. We only use 3.8.10 for Win7 compatibility.
- Nexus Worksheet API no longer fails if the file is not a supported IG-XL file format. Now it just returns None.
- Nexus Worksheet API filter conditions no longer raise Exception when the data is not defined. The value just fails the match condition.
- Installed openpyxl for Excel worksheet support.
- Changed program definition Converters to Interposers.
- Added support for dynamic interposers and added FlowSelector eng interposer.
- Improved error reporting in Explorer.
- Explorer Script tab renamed to Tools.
- Improved error reporting in file system module. Also ignore invalid character errors. Now just treat them as "unreadable characters". This fixes a compatibility bug for non-utf8 base encodings.
